#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AssaultClass_A

#include "Basic.hpp"

#include "BP_AssaultClass_A_classes.hpp"
#include "BP_AssaultClass_A_parameters.hpp"


namespace SDK
{

// Function BP_AssaultClass_A.BP_AssaultClass_A_C.ExecuteUbergraph_BP_AssaultClass_A
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AssaultClass_A_C::ExecuteUbergraph_BP_AssaultClass_A(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AssaultClass_A_C", "ExecuteUbergraph_BP_AssaultClass_A");

	Params::BP_AssaultClass_A_C_ExecuteUbergraph_BP_AssaultClass_A Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AssaultClass_A.BP_AssaultClass_A_C.ThrowItem
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_AssaultClass_A_C::ThrowItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AssaultClass_A_C", "ThrowItem");

	UObject::ProcessEvent(Func, nullptr);
}

}

