#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AI_Character_A

#include "Basic.hpp"

#include "BP_Base_AI_Character_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AI_Character_A.BP_AI_Character_A_C
// 0x0000 (0x07B0 - 0x07B0)
class ABP_AI_Character_A_C final : public ABP_Base_AI_Character_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AI_Character_A_C">();
	}
	static class ABP_AI_Character_A_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_AI_Character_A_C>();
	}
};
static_assert(alignof(ABP_AI_Character_A_C) == 0x000010, "Wrong alignment on ABP_AI_Character_A_C");
static_assert(sizeof(ABP_AI_Character_A_C) == 0x0007B0, "Wrong size on ABP_AI_Character_A_C");

}

