#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BaseLethalEquipment

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_BaseLethalEquipment.BP_BaseLethalEquipment_C.ExecuteUbergraph_BP_BaseLethalEquipment
// 0x008C (0x008C - 0x0000)
struct BP_BaseLethalEquipment_C_ExecuteUbergraph_BP_BaseLethalEquipment final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetRelativeTransform_SweepHitResult;   // 0x0004(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_BaseLethalEquipment_C_ExecuteUbergraph_BP_BaseLethalEquipment) == 0x000004, "Wrong alignment on BP_BaseLethalEquipment_C_ExecuteUbergraph_BP_BaseLethalEquipment");
static_assert(sizeof(BP_BaseLethalEquipment_C_ExecuteUbergraph_BP_BaseLethalEquipment) == 0x00008C, "Wrong size on BP_BaseLethalEquipment_C_ExecuteUbergraph_BP_BaseLethalEquipment");
static_assert(offsetof(BP_BaseLethalEquipment_C_ExecuteUbergraph_BP_BaseLethalEquipment, EntryPoint) == 0x000000, "Member 'BP_BaseLethalEquipment_C_ExecuteUbergraph_BP_BaseLethalEquipment::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_BaseLethalEquipment_C_ExecuteUbergraph_BP_BaseLethalEquipment, CallFunc_K2_SetRelativeTransform_SweepHitResult) == 0x000004, "Member 'BP_BaseLethalEquipment_C_ExecuteUbergraph_BP_BaseLethalEquipment::CallFunc_K2_SetRelativeTransform_SweepHitResult' has a wrong offset!");

}

