#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Base_Objective

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Base_Objective.BP_Base_Objective_C.ExecuteUbergraph_BP_Base_Objective
// 0x0004 (0x0004 - 0x0000)
struct BP_Base_Objective_C_ExecuteUbergraph_BP_Base_Objective final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Base_Objective_C_ExecuteUbergraph_BP_Base_Objective) == 0x000004, "Wrong alignment on BP_Base_Objective_C_ExecuteUbergraph_BP_Base_Objective");
static_assert(sizeof(BP_Base_Objective_C_ExecuteUbergraph_BP_Base_Objective) == 0x000004, "Wrong size on BP_Base_Objective_C_ExecuteUbergraph_BP_Base_Objective");
static_assert(offsetof(BP_Base_Objective_C_ExecuteUbergraph_BP_Base_Objective, EntryPoint) == 0x000000, "Member 'BP_Base_Objective_C_ExecuteUbergraph_BP_Base_Objective::EntryPoint' has a wrong offset!");

}

