#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CheatManager

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CheatManager.BP_CheatManager_C
// 0x0018 (0x00A0 - 0x0088)
class UBP_CheatManager_C final : public UCheatManager
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0088(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_BasePlayerController_C*             PC;                                                // 0x0090(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_Base_GM_C*                          GM;                                                // 0x0098(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void NoCoolDown();
	void ReceiveInitCheatManager();
	void InfiniteExplosives();
	void InfiniteClip();
	void RestartLevel();
	void ExecuteUbergraph_BP_CheatManager(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CheatManager_C">();
	}
	static class UBP_CheatManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CheatManager_C>();
	}
};
static_assert(alignof(UBP_CheatManager_C) == 0x000008, "Wrong alignment on UBP_CheatManager_C");
static_assert(sizeof(UBP_CheatManager_C) == 0x0000A0, "Wrong size on UBP_CheatManager_C");
static_assert(offsetof(UBP_CheatManager_C, UberGraphFrame) == 0x000088, "Member 'UBP_CheatManager_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_CheatManager_C, PC) == 0x000090, "Member 'UBP_CheatManager_C::PC' has a wrong offset!");
static_assert(offsetof(UBP_CheatManager_C, GM) == 0x000098, "Member 'UBP_CheatManager_C::GM' has a wrong offset!");

}

