#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ClaymoreLethal

#include "Basic.hpp"

#include "BP_ClaymoreLethal_classes.hpp"
#include "BP_ClaymoreLethal_parameters.hpp"


namespace SDK
{

// Function BP_ClaymoreLethal.BP_ClaymoreLethal_C.OnRelease
// (BlueprintCallable, BlueprintEvent)

void ABP_ClaymoreLethal_C::OnRelease()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClaymoreLethal_C", "OnRelease");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ClaymoreLethal.BP_ClaymoreLethal_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_ClaymoreLethal_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClaymoreLethal_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ClaymoreLethal.BP_ClaymoreLethal_C.Spawn Claymore
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_ClaymoreLethal_C::Spawn_Claymore()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClaymoreLethal_C", "Spawn Claymore");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ClaymoreLethal.BP_ClaymoreLethal_C.Client_ReduceLethalAmmo
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)

void ABP_ClaymoreLethal_C::Client_ReduceLethalAmmo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClaymoreLethal_C", "Client_ReduceLethalAmmo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ClaymoreLethal.BP_ClaymoreLethal_C.Client_ShowFailMessage
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)

void ABP_ClaymoreLethal_C::Client_ShowFailMessage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClaymoreLethal_C", "Client_ShowFailMessage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ClaymoreLethal.BP_ClaymoreLethal_C.ExecuteUbergraph_BP_ClaymoreLethal
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ClaymoreLethal_C::ExecuteUbergraph_BP_ClaymoreLethal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClaymoreLethal_C", "ExecuteUbergraph_BP_ClaymoreLethal");

	Params::BP_ClaymoreLethal_C_ExecuteUbergraph_BP_ClaymoreLethal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

