#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ConquestCapturePoint

#include "Basic.hpp"

#include "BP_ConquestCapturePoint_classes.hpp"
#include "BP_ConquestCapturePoint_parameters.hpp"


namespace SDK
{

// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.SecurePoint
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ConquestCapturePoint_C::SecurePoint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "SecurePoint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.SetNewState
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ConquestCapturePoint_C::SetNewState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "SetNewState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.CapturePoint
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECapturePointState                      NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ConquestCapturePoint_C::CapturePoint(ECapturePointState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "CapturePoint");

	Params::BP_ConquestCapturePoint_C_CapturePoint Parms{};

	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.SetState
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ConquestCapturePoint_C::SetState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "SetState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.Neutral
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ConquestCapturePoint_C::Neutral()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "Neutral");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.InitCapturePoint
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ConquestCapturePoint_C::InitCapturePoint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "InitCapturePoint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.RecoverLastState
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ConquestCapturePoint_C::RecoverLastState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "RecoverLastState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.OnRep_FlagState
// (BlueprintCallable, BlueprintEvent)

void ABP_ConquestCapturePoint_C::OnRep_FlagState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "OnRep_FlagState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.GetPlayersInside
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_ConquestCapturePoint_C::GetPlayersInside()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "GetPlayersInside");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_ConquestCapturePoint_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_ConquestCapturePoint_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.Increase Team Points
// (BlueprintCallable, BlueprintEvent)

void ABP_ConquestCapturePoint_C::Increase_Team_Points()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "Increase Team Points");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.BndEvt__Sphere_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FHitResult                       SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_ConquestCapturePoint_C::BndEvt__Sphere_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "BndEvt__Sphere_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_ConquestCapturePoint_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.BndEvt__Sphere_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ConquestCapturePoint_C::BndEvt__Sphere_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "BndEvt__Sphere_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature");

	Params::BP_ConquestCapturePoint_C_BndEvt__Sphere_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.Client_ChangeFlagMat
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECapturePointState                      NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ConquestCapturePoint_C::Client_ChangeFlagMat(ECapturePointState NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "Client_ChangeFlagMat");

	Params::BP_ConquestCapturePoint_C_Client_ChangeFlagMat Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.Server_GivePoints
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bTeam                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   Score                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ERewardReasons                          Reason                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ConquestCapturePoint_C::Server_GivePoints(bool bTeam, float Score, ERewardReasons Reason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "Server_GivePoints");

	Params::BP_ConquestCapturePoint_C_Server_GivePoints Parms{};

	Parms.bTeam = bTeam;
	Parms.Score = Score;
	Parms.Reason = Reason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.Client_SetIconColor
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECapturePointState                      State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ConquestCapturePoint_C::Client_SetIconColor(ECapturePointState State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "Client_SetIconColor");

	Params::BP_ConquestCapturePoint_C_Client_SetIconColor Parms{};

	Parms.State = State;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.Set Icon
// (BlueprintCallable, BlueprintEvent)

void ABP_ConquestCapturePoint_C::Set_Icon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "Set Icon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.AddPoints
// (BlueprintCallable, BlueprintEvent)

void ABP_ConquestCapturePoint_C::AddPoints()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "AddPoints");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.FlagUpdatePoints
// (BlueprintCallable, BlueprintEvent)

void ABP_ConquestCapturePoint_C::FlagUpdatePoints()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "FlagUpdatePoints");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.SetPointPorgress
// (BlueprintCallable, BlueprintEvent)

void ABP_ConquestCapturePoint_C::SetPointPorgress()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "SetPointPorgress");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.WidgetStartAnimation
// (BlueprintCallable, BlueprintEvent)

void ABP_ConquestCapturePoint_C::WidgetStartAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "WidgetStartAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.WidgetStopAnimation
// (BlueprintCallable, BlueprintEvent)

void ABP_ConquestCapturePoint_C::WidgetStopAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "WidgetStopAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestCapturePoint.BP_ConquestCapturePoint_C.ExecuteUbergraph_BP_ConquestCapturePoint
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ConquestCapturePoint_C::ExecuteUbergraph_BP_ConquestCapturePoint(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestCapturePoint_C", "ExecuteUbergraph_BP_ConquestCapturePoint");

	Params::BP_ConquestCapturePoint_C_ExecuteUbergraph_BP_ConquestCapturePoint Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

