#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Conquest_GM

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Conquest_GM.BP_Conquest_GM_C.ExecuteUbergraph_BP_Conquest_GM
// 0x0004 (0x0004 - 0x0000)
struct BP_Conquest_GM_C_ExecuteUbergraph_BP_Conquest_GM final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Conquest_GM_C_ExecuteUbergraph_BP_Conquest_GM) == 0x000004, "Wrong alignment on BP_Conquest_GM_C_ExecuteUbergraph_BP_Conquest_GM");
static_assert(sizeof(BP_Conquest_GM_C_ExecuteUbergraph_BP_Conquest_GM) == 0x000004, "Wrong size on BP_Conquest_GM_C_ExecuteUbergraph_BP_Conquest_GM");
static_assert(offsetof(BP_Conquest_GM_C_ExecuteUbergraph_BP_Conquest_GM, EntryPoint) == 0x000000, "Member 'BP_Conquest_GM_C_ExecuteUbergraph_BP_Conquest_GM::EntryPoint' has a wrong offset!");

}

