#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FragGrenade

#include "Basic.hpp"

#include "BP_FragGrenade_classes.hpp"
#include "BP_FragGrenade_parameters.hpp"


namespace SDK
{

// Function BP_FragGrenade.BP_FragGrenade_C.SetProjectileVelocity
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_FragGrenade_C::SetProjectileVelocity()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FragGrenade_C", "SetProjectileVelocity");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FragGrenade.BP_FragGrenade_C.OnRep_bExploded
// (BlueprintCallable, BlueprintEvent)

void ABP_FragGrenade_C::OnRep_bExploded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FragGrenade_C", "OnRep_bExploded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FragGrenade.BP_FragGrenade_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_FragGrenade_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FragGrenade_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FragGrenade.BP_FragGrenade_C.Multicast_PlayEffects
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_FragGrenade_C::Multicast_PlayEffects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FragGrenade_C", "Multicast_PlayEffects");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FragGrenade.BP_FragGrenade_C.ReceiveAnyDamage
// (BlueprintAuthorityOnly, Event, Public, BlueprintEvent)
// Parameters:
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UDamageType*                      DamageType                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AController*                      InstigatedBy                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FragGrenade_C::ReceiveAnyDamage(float Damage, const class UDamageType* DamageType, class AController* InstigatedBy, class AActor* DamageCauser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FragGrenade_C", "ReceiveAnyDamage");

	Params::BP_FragGrenade_C_ReceiveAnyDamage Parms{};

	Parms.Damage = Damage;
	Parms.DamageType = DamageType;
	Parms.InstigatedBy = InstigatedBy;
	Parms.DamageCauser = DamageCauser;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FragGrenade.BP_FragGrenade_C.ExplodeGrenade
// (BlueprintCallable, BlueprintEvent)

void ABP_FragGrenade_C::ExplodeGrenade()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FragGrenade_C", "ExplodeGrenade");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FragGrenade.BP_FragGrenade_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_FragGrenade_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FragGrenade_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FragGrenade.BP_FragGrenade_C.OnExploded
// (BlueprintCallable, BlueprintEvent)

void ABP_FragGrenade_C::OnExploded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FragGrenade_C", "OnExploded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FragGrenade.BP_FragGrenade_C.Explode
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AController*                      Instigator_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FragGrenade_C::Explode(class AController* Instigator_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FragGrenade_C", "Explode");

	Params::BP_FragGrenade_C_Explode Parms{};

	Parms.Instigator_0 = Instigator_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FragGrenade.BP_FragGrenade_C.ExecuteUbergraph_BP_FragGrenade
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FragGrenade_C::ExecuteUbergraph_BP_FragGrenade(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FragGrenade_C", "ExecuteUbergraph_BP_FragGrenade");

	Params::BP_FragGrenade_C_ExecuteUbergraph_BP_FragGrenade Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

