#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameInstance

#include "Basic.hpp"

#include "BP_GameInstance_classes.hpp"
#include "BP_GameInstance_parameters.hpp"


namespace SDK
{

// Function BP_GameInstance.BP_GameInstance_C.ExecuteUbergraph_BP_GameInstance
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_GameInstance_C::ExecuteUbergraph_BP_GameInstance(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameInstance_C", "ExecuteUbergraph_BP_GameInstance");

	Params::BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameInstance.BP_GameInstance_C.JoinServer
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FBlueprintSessionResult          SessionToJoin                                          (BlueprintVisible, BlueprintReadOnly, Parm)

void UBP_GameInstance_C::JoinServer(const struct FBlueprintSessionResult& SessionToJoin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameInstance_C", "JoinServer");

	Params::BP_GameInstance_C_JoinServer Parms{};

	Parms.SessionToJoin = std::move(SessionToJoin);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameInstance.BP_GameInstance_C.DestroySessionCaller
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_GameInstance_C::DestroySessionCaller(class APlayerController* PlayerController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameInstance_C", "DestroySessionCaller");

	Params::BP_GameInstance_C_DestroySessionCaller Parms{};

	Parms.PlayerController = PlayerController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameInstance.BP_GameInstance_C.OnSuccess_5662C0584E0AE12FB90219B012FE5C60
// (BlueprintCallable, BlueprintEvent)

void UBP_GameInstance_C::OnSuccess_5662C0584E0AE12FB90219B012FE5C60()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameInstance_C", "OnSuccess_5662C0584E0AE12FB90219B012FE5C60");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GameInstance.BP_GameInstance_C.OnFailure_5662C0584E0AE12FB90219B012FE5C60
// (BlueprintCallable, BlueprintEvent)

void UBP_GameInstance_C::OnFailure_5662C0584E0AE12FB90219B012FE5C60()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameInstance_C", "OnFailure_5662C0584E0AE12FB90219B012FE5C60");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GameInstance.BP_GameInstance_C.OnSuccess_FEB1A1304CDE2ED6CC6C06A948930758
// (BlueprintCallable, BlueprintEvent)

void UBP_GameInstance_C::OnSuccess_FEB1A1304CDE2ED6CC6C06A948930758()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameInstance_C", "OnSuccess_FEB1A1304CDE2ED6CC6C06A948930758");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GameInstance.BP_GameInstance_C.OnFailure_FEB1A1304CDE2ED6CC6C06A948930758
// (BlueprintCallable, BlueprintEvent)

void UBP_GameInstance_C::OnFailure_FEB1A1304CDE2ED6CC6C06A948930758()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameInstance_C", "OnFailure_FEB1A1304CDE2ED6CC6C06A948930758");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GameInstance.BP_GameInstance_C.NetErrorToString
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ENetworkFailure                         Failure_Type                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           NewParam                                               (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UBP_GameInstance_C::NetErrorToString(ENetworkFailure Failure_Type, class FString* NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameInstance_C", "NetErrorToString");

	Params::BP_GameInstance_C_NetErrorToString Parms{};

	Parms.Failure_Type = Failure_Type;

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = std::move(Parms.NewParam);
}


// Function BP_GameInstance.BP_GameInstance_C.TravelErrorToString
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ETravelFailure                          Travel_Error                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           OutString                                              (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UBP_GameInstance_C::TravelErrorToString(ETravelFailure Travel_Error, class FString* OutString)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameInstance_C", "TravelErrorToString");

	Params::BP_GameInstance_C_TravelErrorToString Parms{};

	Parms.Travel_Error = Travel_Error;

	UObject::ProcessEvent(Func, &Parms);

	if (OutString != nullptr)
		*OutString = std::move(Parms.OutString);
}

}

