#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameInstance

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OnlineSubsystemUtils_structs.hpp"


namespace SDK::Params
{

// Function BP_GameInstance.BP_GameInstance_C.ExecuteUbergraph_BP_GameInstance
// 0x0180 (0x0180 - 0x0000)
struct BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0024(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      K2Node_CustomEvent_PlayerController;               // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBlueprintSessionResult                K2Node_CustomEvent_SessionToJoin;                  // 0x0048(0x0108)()
	class UDestroySessionCallbackProxy*           CallFunc_DestroySession_ReturnValue;               // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UJoinSessionCallbackProxy*              CallFunc_JoinSession_ReturnValue;                  // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0161(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_162[0x2];                                      // 0x0162(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetCurrentPlayers_ReturnValue;            // 0x0164(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_169[0x3];                                      // 0x0169(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x016C(0x0010)(ZeroConstructor, NoDestructor)
};
static_assert(alignof(BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance) == 0x000008, "Wrong alignment on BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance");
static_assert(sizeof(BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance) == 0x000180, "Wrong size on BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance");
static_assert(offsetof(BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance, EntryPoint) == 0x000000, "Member 'BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance, K2Node_CreateDelegate_OutputDelegate_1) == 0x000014, "Member 'BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance, K2Node_CreateDelegate_OutputDelegate_2) == 0x000024, "Member 'BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance, CallFunc_GetPlayerController_ReturnValue) == 0x000038, "Member 'BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance, K2Node_CustomEvent_PlayerController) == 0x000040, "Member 'BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance::K2Node_CustomEvent_PlayerController' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance, K2Node_CustomEvent_SessionToJoin) == 0x000048, "Member 'BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance::K2Node_CustomEvent_SessionToJoin' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance, CallFunc_DestroySession_ReturnValue) == 0x000150, "Member 'BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance::CallFunc_DestroySession_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance, CallFunc_JoinSession_ReturnValue) == 0x000158, "Member 'BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance::CallFunc_JoinSession_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance, CallFunc_IsValid_ReturnValue) == 0x000160, "Member 'BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance, CallFunc_IsValid_ReturnValue_1) == 0x000161, "Member 'BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance, CallFunc_GetCurrentPlayers_ReturnValue) == 0x000164, "Member 'BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance::CallFunc_GetCurrentPlayers_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance, CallFunc_Greater_IntInt_ReturnValue) == 0x000168, "Member 'BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance, K2Node_CreateDelegate_OutputDelegate_3) == 0x00016C, "Member 'BP_GameInstance_C_ExecuteUbergraph_BP_GameInstance::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");

// Function BP_GameInstance.BP_GameInstance_C.JoinServer
// 0x0108 (0x0108 - 0x0000)
struct BP_GameInstance_C_JoinServer final
{
public:
	struct FBlueprintSessionResult                SessionToJoin;                                     // 0x0000(0x0108)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(BP_GameInstance_C_JoinServer) == 0x000008, "Wrong alignment on BP_GameInstance_C_JoinServer");
static_assert(sizeof(BP_GameInstance_C_JoinServer) == 0x000108, "Wrong size on BP_GameInstance_C_JoinServer");
static_assert(offsetof(BP_GameInstance_C_JoinServer, SessionToJoin) == 0x000000, "Member 'BP_GameInstance_C_JoinServer::SessionToJoin' has a wrong offset!");

// Function BP_GameInstance.BP_GameInstance_C.DestroySessionCaller
// 0x0008 (0x0008 - 0x0000)
struct BP_GameInstance_C_DestroySessionCaller final
{
public:
	class APlayerController*                      PlayerController;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GameInstance_C_DestroySessionCaller) == 0x000008, "Wrong alignment on BP_GameInstance_C_DestroySessionCaller");
static_assert(sizeof(BP_GameInstance_C_DestroySessionCaller) == 0x000008, "Wrong size on BP_GameInstance_C_DestroySessionCaller");
static_assert(offsetof(BP_GameInstance_C_DestroySessionCaller, PlayerController) == 0x000000, "Member 'BP_GameInstance_C_DestroySessionCaller::PlayerController' has a wrong offset!");

// Function BP_GameInstance.BP_GameInstance_C.NetErrorToString
// 0x0028 (0x0028 - 0x0000)
struct BP_GameInstance_C_NetErrorToString final
{
public:
	ENetworkFailure                               Failure_Type;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 NewParam;                                          // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetEnumeratorUserFriendlyName_ReturnValue; // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GameInstance_C_NetErrorToString) == 0x000008, "Wrong alignment on BP_GameInstance_C_NetErrorToString");
static_assert(sizeof(BP_GameInstance_C_NetErrorToString) == 0x000028, "Wrong size on BP_GameInstance_C_NetErrorToString");
static_assert(offsetof(BP_GameInstance_C_NetErrorToString, Failure_Type) == 0x000000, "Member 'BP_GameInstance_C_NetErrorToString::Failure_Type' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_NetErrorToString, NewParam) == 0x000008, "Member 'BP_GameInstance_C_NetErrorToString::NewParam' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_NetErrorToString, CallFunc_GetEnumeratorUserFriendlyName_ReturnValue) == 0x000018, "Member 'BP_GameInstance_C_NetErrorToString::CallFunc_GetEnumeratorUserFriendlyName_ReturnValue' has a wrong offset!");

// Function BP_GameInstance.BP_GameInstance_C.TravelErrorToString
// 0x0028 (0x0028 - 0x0000)
struct BP_GameInstance_C_TravelErrorToString final
{
public:
	ETravelFailure                                Travel_Error;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 OutString;                                         // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetEnumeratorUserFriendlyName_ReturnValue; // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GameInstance_C_TravelErrorToString) == 0x000008, "Wrong alignment on BP_GameInstance_C_TravelErrorToString");
static_assert(sizeof(BP_GameInstance_C_TravelErrorToString) == 0x000028, "Wrong size on BP_GameInstance_C_TravelErrorToString");
static_assert(offsetof(BP_GameInstance_C_TravelErrorToString, Travel_Error) == 0x000000, "Member 'BP_GameInstance_C_TravelErrorToString::Travel_Error' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_TravelErrorToString, OutString) == 0x000008, "Member 'BP_GameInstance_C_TravelErrorToString::OutString' has a wrong offset!");
static_assert(offsetof(BP_GameInstance_C_TravelErrorToString, CallFunc_GetEnumeratorUserFriendlyName_ReturnValue) == 0x000018, "Member 'BP_GameInstance_C_TravelErrorToString::CallFunc_GetEnumeratorUserFriendlyName_ReturnValue' has a wrong offset!");

}

