#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ImpactGrenadeLethal

#include "Basic.hpp"

#include "BP_ImpactGrenadeLethal_classes.hpp"
#include "BP_ImpactGrenadeLethal_parameters.hpp"


namespace SDK
{

// Function BP_ImpactGrenadeLethal.BP_ImpactGrenadeLethal_C.Activate
// (BlueprintCallable, BlueprintEvent)

void ABP_ImpactGrenadeLethal_C::Activate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ImpactGrenadeLethal_C", "Activate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ImpactGrenadeLethal.BP_ImpactGrenadeLethal_C.OnRelease
// (BlueprintCallable, BlueprintEvent)

void ABP_ImpactGrenadeLethal_C::OnRelease()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ImpactGrenadeLethal_C", "OnRelease");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ImpactGrenadeLethal.BP_ImpactGrenadeLethal_C.ReleaseLethal
// (BlueprintCallable, BlueprintEvent)

void ABP_ImpactGrenadeLethal_C::ReleaseLethal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ImpactGrenadeLethal_C", "ReleaseLethal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ImpactGrenadeLethal.BP_ImpactGrenadeLethal_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_ImpactGrenadeLethal_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ImpactGrenadeLethal_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ImpactGrenadeLethal.BP_ImpactGrenadeLethal_C.ExplodeGrenade
// (BlueprintCallable, BlueprintEvent)

void ABP_ImpactGrenadeLethal_C::ExplodeGrenade()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ImpactGrenadeLethal_C", "ExplodeGrenade");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ImpactGrenadeLethal.BP_ImpactGrenadeLethal_C.Server_SpawnGrenade
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   TimeLeft                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Spawn_Transform_Location                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ImpactGrenadeLethal_C::Server_SpawnGrenade(float TimeLeft, const struct FVector& Spawn_Transform_Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ImpactGrenadeLethal_C", "Server_SpawnGrenade");

	Params::BP_ImpactGrenadeLethal_C_Server_SpawnGrenade Parms{};

	Parms.TimeLeft = TimeLeft;
	Parms.Spawn_Transform_Location = std::move(Spawn_Transform_Location);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ImpactGrenadeLethal.BP_ImpactGrenadeLethal_C.Reset
// (BlueprintCallable, BlueprintEvent)

void ABP_ImpactGrenadeLethal_C::Reset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ImpactGrenadeLethal_C", "Reset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ImpactGrenadeLethal.BP_ImpactGrenadeLethal_C.Client_ReduceLethalAmmo
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)

void ABP_ImpactGrenadeLethal_C::Client_ReduceLethalAmmo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ImpactGrenadeLethal_C", "Client_ReduceLethalAmmo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ImpactGrenadeLethal.BP_ImpactGrenadeLethal_C.DropLethal
// (BlueprintCallable, BlueprintEvent)

void ABP_ImpactGrenadeLethal_C::DropLethal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ImpactGrenadeLethal_C", "DropLethal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ImpactGrenadeLethal.BP_ImpactGrenadeLethal_C.ExecuteUbergraph_BP_ImpactGrenadeLethal
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ImpactGrenadeLethal_C::ExecuteUbergraph_BP_ImpactGrenadeLethal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ImpactGrenadeLethal_C", "ExecuteUbergraph_BP_ImpactGrenadeLethal");

	Params::BP_ImpactGrenadeLethal_C_ExecuteUbergraph_BP_ImpactGrenadeLethal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

