#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SpectatorBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SpectatorBase.BP_SpectatorBase_C
// 0x0018 (0x0298 - 0x0280)
class ABP_SpectatorBase_C final : public APawn
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USpringArmComponent*                    SpringArm;                                         // 0x0288(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCameraComponent*                       Camera;                                            // 0x0290(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void InpAxisEvt_LookUp_K2Node_InputAxisEvent_0(float AxisValue);
	void InpAxisEvt_Turn_K2Node_InputAxisEvent_1(float AxisValue);
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_SpectatorBase(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SpectatorBase_C">();
	}
	static class ABP_SpectatorBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SpectatorBase_C>();
	}
};
static_assert(alignof(ABP_SpectatorBase_C) == 0x000008, "Wrong alignment on ABP_SpectatorBase_C");
static_assert(sizeof(ABP_SpectatorBase_C) == 0x000298, "Wrong size on ABP_SpectatorBase_C");
static_assert(offsetof(ABP_SpectatorBase_C, UberGraphFrame) == 0x000280, "Member 'ABP_SpectatorBase_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_SpectatorBase_C, SpringArm) == 0x000288, "Member 'ABP_SpectatorBase_C::SpringArm' has a wrong offset!");
static_assert(offsetof(ABP_SpectatorBase_C, Camera) == 0x000290, "Member 'ABP_SpectatorBase_C::Camera' has a wrong offset!");

}

