#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SupportClass_A

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_SupportClass_A.BP_SupportClass_A_C.ExecuteUbergraph_BP_SupportClass_A
// 0x0004 (0x0004 - 0x0000)
struct BP_SupportClass_A_C_ExecuteUbergraph_BP_SupportClass_A final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SupportClass_A_C_ExecuteUbergraph_BP_SupportClass_A) == 0x000004, "Wrong alignment on BP_SupportClass_A_C_ExecuteUbergraph_BP_SupportClass_A");
static_assert(sizeof(BP_SupportClass_A_C_ExecuteUbergraph_BP_SupportClass_A) == 0x000004, "Wrong size on BP_SupportClass_A_C_ExecuteUbergraph_BP_SupportClass_A");
static_assert(offsetof(BP_SupportClass_A_C_ExecuteUbergraph_BP_SupportClass_A, EntryPoint) == 0x000000, "Member 'BP_SupportClass_A_C_ExecuteUbergraph_BP_SupportClass_A::EntryPoint' has a wrong offset!");

}

