#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPT_MoveToReachableRandomPoint

#include "Basic.hpp"

#include "BPT_MoveToReachableRandomPoint_classes.hpp"
#include "BPT_MoveToReachableRandomPoint_parameters.hpp"


namespace SDK
{

// Function BPT_MoveToReachableRandomPoint.BPT_MoveToReachableRandomPoint_C.ReceiveExecuteAI
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AAIController*                    OwnerController                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPT_MoveToReachableRandomPoint_C::ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPT_MoveToReachableRandomPoint_C", "ReceiveExecuteAI");

	Params::BPT_MoveToReachableRandomPoint_C_ReceiveExecuteAI Parms{};

	Parms.OwnerController = OwnerController;
	Parms.ControlledPawn = ControlledPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPT_MoveToReachableRandomPoint.BPT_MoveToReachableRandomPoint_C.ReceiveAbortAI
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AAIController*                    OwnerController                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPT_MoveToReachableRandomPoint_C::ReceiveAbortAI(class AAIController* OwnerController, class APawn* ControlledPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPT_MoveToReachableRandomPoint_C", "ReceiveAbortAI");

	Params::BPT_MoveToReachableRandomPoint_C_ReceiveAbortAI Parms{};

	Parms.OwnerController = OwnerController;
	Parms.ControlledPawn = ControlledPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPT_MoveToReachableRandomPoint.BPT_MoveToReachableRandomPoint_C.ExecuteUbergraph_BPT_MoveToReachableRandomPoint
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPT_MoveToReachableRandomPoint_C::ExecuteUbergraph_BPT_MoveToReachableRandomPoint(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPT_MoveToReachableRandomPoint_C", "ExecuteUbergraph_BPT_MoveToReachableRandomPoint");

	Params::BPT_MoveToReachableRandomPoint_C_ExecuteUbergraph_BPT_MoveToReachableRandomPoint Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

