#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPT_UseMelee

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPT_UseMelee.BPT_UseMelee_C.SetRunning
// 0x0028 (0x0028 - 0x0000)
struct BPT_UseMelee_C_SetRunning final
{
public:
	class APawn*                                  Pawn;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bRun;                                              // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_BaseCharacter_C*                    K2Node_DynamicCast_AsBP_Base_Character;            // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable;                               // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_1;                             // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default;                             // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPT_UseMelee_C_SetRunning) == 0x000008, "Wrong alignment on BPT_UseMelee_C_SetRunning");
static_assert(sizeof(BPT_UseMelee_C_SetRunning) == 0x000028, "Wrong size on BPT_UseMelee_C_SetRunning");
static_assert(offsetof(BPT_UseMelee_C_SetRunning, Pawn) == 0x000000, "Member 'BPT_UseMelee_C_SetRunning::Pawn' has a wrong offset!");
static_assert(offsetof(BPT_UseMelee_C_SetRunning, bRun) == 0x000008, "Member 'BPT_UseMelee_C_SetRunning::bRun' has a wrong offset!");
static_assert(offsetof(BPT_UseMelee_C_SetRunning, Temp_bool_Variable) == 0x000009, "Member 'BPT_UseMelee_C_SetRunning::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BPT_UseMelee_C_SetRunning, K2Node_DynamicCast_AsBP_Base_Character) == 0x000010, "Member 'BPT_UseMelee_C_SetRunning::K2Node_DynamicCast_AsBP_Base_Character' has a wrong offset!");
static_assert(offsetof(BPT_UseMelee_C_SetRunning, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'BPT_UseMelee_C_SetRunning::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BPT_UseMelee_C_SetRunning, Temp_float_Variable) == 0x00001C, "Member 'BPT_UseMelee_C_SetRunning::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(BPT_UseMelee_C_SetRunning, Temp_float_Variable_1) == 0x000020, "Member 'BPT_UseMelee_C_SetRunning::Temp_float_Variable_1' has a wrong offset!");
static_assert(offsetof(BPT_UseMelee_C_SetRunning, K2Node_Select_Default) == 0x000024, "Member 'BPT_UseMelee_C_SetRunning::K2Node_Select_Default' has a wrong offset!");

// Function BPT_UseMelee.BPT_UseMelee_C.ReceiveExecuteAI
// 0x0010 (0x0010 - 0x0000)
struct BPT_UseMelee_C_ReceiveExecuteAI final
{
public:
	class AAIController*                          OwnerController;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  ControlledPawn;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPT_UseMelee_C_ReceiveExecuteAI) == 0x000008, "Wrong alignment on BPT_UseMelee_C_ReceiveExecuteAI");
static_assert(sizeof(BPT_UseMelee_C_ReceiveExecuteAI) == 0x000010, "Wrong size on BPT_UseMelee_C_ReceiveExecuteAI");
static_assert(offsetof(BPT_UseMelee_C_ReceiveExecuteAI, OwnerController) == 0x000000, "Member 'BPT_UseMelee_C_ReceiveExecuteAI::OwnerController' has a wrong offset!");
static_assert(offsetof(BPT_UseMelee_C_ReceiveExecuteAI, ControlledPawn) == 0x000008, "Member 'BPT_UseMelee_C_ReceiveExecuteAI::ControlledPawn' has a wrong offset!");

// Function BPT_UseMelee.BPT_UseMelee_C.ExecuteUbergraph_BPT_UseMelee
// 0x0030 (0x0030 - 0x0000)
struct BPT_UseMelee_C_ExecuteUbergraph_BPT_UseMelee final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AAIController*                          K2Node_Event_OwnerController;                      // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_ControlledPawn;                       // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IIPawnActions_C>       K2Node_DynamicCast_AsI_Pawn_Actions;               // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BPT_UseMelee_C_ExecuteUbergraph_BPT_UseMelee) == 0x000008, "Wrong alignment on BPT_UseMelee_C_ExecuteUbergraph_BPT_UseMelee");
static_assert(sizeof(BPT_UseMelee_C_ExecuteUbergraph_BPT_UseMelee) == 0x000030, "Wrong size on BPT_UseMelee_C_ExecuteUbergraph_BPT_UseMelee");
static_assert(offsetof(BPT_UseMelee_C_ExecuteUbergraph_BPT_UseMelee, EntryPoint) == 0x000000, "Member 'BPT_UseMelee_C_ExecuteUbergraph_BPT_UseMelee::EntryPoint' has a wrong offset!");
static_assert(offsetof(BPT_UseMelee_C_ExecuteUbergraph_BPT_UseMelee, K2Node_Event_OwnerController) == 0x000008, "Member 'BPT_UseMelee_C_ExecuteUbergraph_BPT_UseMelee::K2Node_Event_OwnerController' has a wrong offset!");
static_assert(offsetof(BPT_UseMelee_C_ExecuteUbergraph_BPT_UseMelee, K2Node_Event_ControlledPawn) == 0x000010, "Member 'BPT_UseMelee_C_ExecuteUbergraph_BPT_UseMelee::K2Node_Event_ControlledPawn' has a wrong offset!");
static_assert(offsetof(BPT_UseMelee_C_ExecuteUbergraph_BPT_UseMelee, K2Node_DynamicCast_AsI_Pawn_Actions) == 0x000018, "Member 'BPT_UseMelee_C_ExecuteUbergraph_BPT_UseMelee::K2Node_DynamicCast_AsI_Pawn_Actions' has a wrong offset!");
static_assert(offsetof(BPT_UseMelee_C_ExecuteUbergraph_BPT_UseMelee, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'BPT_UseMelee_C_ExecuteUbergraph_BPT_UseMelee::K2Node_DynamicCast_bSuccess' has a wrong offset!");

}

