#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPT_MoveToReachableRandomPoint

#include "Basic.hpp"

#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPT_MoveToReachableRandomPoint.BPT_MoveToReachableRandomPoint_C
// 0x0058 (0x0100 - 0x00A8)
class UBPT_MoveToReachableRandomPoint_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FBlackboardKeySelector                 Location;                                          // 0x00B0(0x0028)(Edit, BlueprintVisible)
	struct FBlackboardKeySelector                 Objective;                                         // 0x00D8(0x0028)(Edit, BlueprintVisible)

public:
	void ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn);
	void ReceiveAbortAI(class AAIController* OwnerController, class APawn* ControlledPawn);
	void ExecuteUbergraph_BPT_MoveToReachableRandomPoint(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPT_MoveToReachableRandomPoint_C">();
	}
	static class UBPT_MoveToReachableRandomPoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPT_MoveToReachableRandomPoint_C>();
	}
};
static_assert(alignof(UBPT_MoveToReachableRandomPoint_C) == 0x000008, "Wrong alignment on UBPT_MoveToReachableRandomPoint_C");
static_assert(sizeof(UBPT_MoveToReachableRandomPoint_C) == 0x000100, "Wrong size on UBPT_MoveToReachableRandomPoint_C");
static_assert(offsetof(UBPT_MoveToReachableRandomPoint_C, UberGraphFrame) == 0x0000A8, "Member 'UBPT_MoveToReachableRandomPoint_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBPT_MoveToReachableRandomPoint_C, Location) == 0x0000B0, "Member 'UBPT_MoveToReachableRandomPoint_C::Location' has a wrong offset!");
static_assert(offsetof(UBPT_MoveToReachableRandomPoint_C, Objective) == 0x0000D8, "Member 'UBPT_MoveToReachableRandomPoint_C::Objective' has a wrong offset!");

}

