#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CS_FireWeapon

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CS_FireWeapon.CS_FireWeapon_C
// 0x0000 (0x01B0 - 0x01B0)
class UCS_FireWeapon_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CS_FireWeapon_C">();
	}
	static class UCS_FireWeapon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCS_FireWeapon_C>();
	}
};
static_assert(alignof(UCS_FireWeapon_C) == 0x000010, "Wrong alignment on UCS_FireWeapon_C");
static_assert(sizeof(UCS_FireWeapon_C) == 0x0001B0, "Wrong size on UCS_FireWeapon_C");

}

