#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ECapturePoints

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ECapturePoints.ECapturePoints
// NumValues: 0x0006
enum class ECapturePoints : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	ECapturePoints_MAX                       = 5,
};

}

