#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FPS_SaveGame

#include "Basic.hpp"

#include "SaveGameStructure_structs.hpp"


namespace SDK::Params
{

// Function FPS_SaveGame.FPS_SaveGame_C.SetPlayerSettings
// 0x0030 (0x0030 - 0x0000)
struct FPS_SaveGame_C_SetPlayerSettings final
{
public:
	struct FSaveGameStructure                     PlayerSettings_0;                                  // 0x0000(0x0030)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FPS_SaveGame_C_SetPlayerSettings) == 0x000004, "Wrong alignment on FPS_SaveGame_C_SetPlayerSettings");
static_assert(sizeof(FPS_SaveGame_C_SetPlayerSettings) == 0x000030, "Wrong size on FPS_SaveGame_C_SetPlayerSettings");
static_assert(offsetof(FPS_SaveGame_C_SetPlayerSettings, PlayerSettings_0) == 0x000000, "Member 'FPS_SaveGame_C_SetPlayerSettings::PlayerSettings_0' has a wrong offset!");

// Function FPS_SaveGame.FPS_SaveGame_C.ExecuteUbergraph_FPS_SaveGame
// 0x0034 (0x0034 - 0x0000)
struct FPS_SaveGame_C_ExecuteUbergraph_FPS_SaveGame final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSaveGameStructure                     K2Node_CustomEvent_PlayerSettings;                 // 0x0004(0x0030)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FPS_SaveGame_C_ExecuteUbergraph_FPS_SaveGame) == 0x000004, "Wrong alignment on FPS_SaveGame_C_ExecuteUbergraph_FPS_SaveGame");
static_assert(sizeof(FPS_SaveGame_C_ExecuteUbergraph_FPS_SaveGame) == 0x000034, "Wrong size on FPS_SaveGame_C_ExecuteUbergraph_FPS_SaveGame");
static_assert(offsetof(FPS_SaveGame_C_ExecuteUbergraph_FPS_SaveGame, EntryPoint) == 0x000000, "Member 'FPS_SaveGame_C_ExecuteUbergraph_FPS_SaveGame::EntryPoint' has a wrong offset!");
static_assert(offsetof(FPS_SaveGame_C_ExecuteUbergraph_FPS_SaveGame, K2Node_CustomEvent_PlayerSettings) == 0x000004, "Member 'FPS_SaveGame_C_ExecuteUbergraph_FPS_SaveGame::K2Node_CustomEvent_PlayerSettings' has a wrong offset!");

}

