#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_BaseButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Slate_structs.hpp"
#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_BaseButton.WB_BaseButton_C
// 0x0170 (0x03D0 - 0x0260)
class UWB_BaseButton_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                BaseButton;                                        // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ButtonText;                                        // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   Text;                                              // 0x0278(0x0018)(Edit, BlueprintVisible)
	struct FSlateFontInfo                         DefaultTextFont;                                   // 0x0290(0x0058)(Edit, BlueprintVisible, HasGetValueTypeHash)
	ETextJustify                                  Justification;                                     // 0x02E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2E9[0x7];                                      // 0x02E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	FMulticastInlineDelegateProperty_             OnClicked;                                         // 0x02F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnReleased;                                        // 0x0300(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FSlateFontInfo                         HoveredTextFont;                                   // 0x0310(0x0058)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FSlateColor                            DefaultColor;                                      // 0x0368(0x0028)(Edit, BlueprintVisible)
	struct FSlateColor                            HoveredColor;                                      // 0x0390(0x0028)(Edit, BlueprintVisible)
	struct FLinearColor                           ButtonBackground_Color;                            // 0x03B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             HoveredSound;                                      // 0x03C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void InitButton();
	void BndEvt__WB_BaseButton_BaseButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WB_BaseButton_BaseButton_K2Node_ComponentBoundEvent_2_OnButtonReleasedEvent__DelegateSignature();
	void BndEvt__WB_BaseButton_BaseButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__WB_BaseButton_BaseButton_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature();
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_WB_BaseButton(int32 EntryPoint);
	void OnReleased__DelegateSignature();
	void OnClicked__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_BaseButton_C">();
	}
	static class UWB_BaseButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_BaseButton_C>();
	}
};
static_assert(alignof(UWB_BaseButton_C) == 0x000008, "Wrong alignment on UWB_BaseButton_C");
static_assert(sizeof(UWB_BaseButton_C) == 0x0003D0, "Wrong size on UWB_BaseButton_C");
static_assert(offsetof(UWB_BaseButton_C, UberGraphFrame) == 0x000260, "Member 'UWB_BaseButton_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWB_BaseButton_C, BaseButton) == 0x000268, "Member 'UWB_BaseButton_C::BaseButton' has a wrong offset!");
static_assert(offsetof(UWB_BaseButton_C, ButtonText) == 0x000270, "Member 'UWB_BaseButton_C::ButtonText' has a wrong offset!");
static_assert(offsetof(UWB_BaseButton_C, Text) == 0x000278, "Member 'UWB_BaseButton_C::Text' has a wrong offset!");
static_assert(offsetof(UWB_BaseButton_C, DefaultTextFont) == 0x000290, "Member 'UWB_BaseButton_C::DefaultTextFont' has a wrong offset!");
static_assert(offsetof(UWB_BaseButton_C, Justification) == 0x0002E8, "Member 'UWB_BaseButton_C::Justification' has a wrong offset!");
static_assert(offsetof(UWB_BaseButton_C, OnClicked) == 0x0002F0, "Member 'UWB_BaseButton_C::OnClicked' has a wrong offset!");
static_assert(offsetof(UWB_BaseButton_C, OnReleased) == 0x000300, "Member 'UWB_BaseButton_C::OnReleased' has a wrong offset!");
static_assert(offsetof(UWB_BaseButton_C, HoveredTextFont) == 0x000310, "Member 'UWB_BaseButton_C::HoveredTextFont' has a wrong offset!");
static_assert(offsetof(UWB_BaseButton_C, DefaultColor) == 0x000368, "Member 'UWB_BaseButton_C::DefaultColor' has a wrong offset!");
static_assert(offsetof(UWB_BaseButton_C, HoveredColor) == 0x000390, "Member 'UWB_BaseButton_C::HoveredColor' has a wrong offset!");
static_assert(offsetof(UWB_BaseButton_C, ButtonBackground_Color) == 0x0003B8, "Member 'UWB_BaseButton_C::ButtonBackground_Color' has a wrong offset!");
static_assert(offsetof(UWB_BaseButton_C, HoveredSound) == 0x0003C8, "Member 'UWB_BaseButton_C::HoveredSound' has a wrong offset!");

}

