#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_ClaymoreFailmessage

#include "Basic.hpp"

#include "WB_ClaymoreFailmessage_classes.hpp"
#include "WB_ClaymoreFailmessage_parameters.hpp"


namespace SDK
{

// Function WB_ClaymoreFailmessage.WB_ClaymoreFailmessage_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWB_ClaymoreFailmessage_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ClaymoreFailmessage_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_ClaymoreFailmessage.WB_ClaymoreFailmessage_C.ExecuteUbergraph_WB_ClaymoreFailmessage
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_ClaymoreFailmessage_C::ExecuteUbergraph_WB_ClaymoreFailmessage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ClaymoreFailmessage_C", "ExecuteUbergraph_WB_ClaymoreFailmessage");

	Params::WB_ClaymoreFailmessage_C_ExecuteUbergraph_WB_ClaymoreFailmessage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

