#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_CaptureTheFlag_World_Widget

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WB_CaptureTheFlag_World_Widget.WB_CaptureTheFlag_World_Widget_C.SetText
// 0x0018 (0x0018 - 0x0000)
struct WB_CaptureTheFlag_World_Widget_C_SetText final
{
public:
	class FText                                   NewText;                                           // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(WB_CaptureTheFlag_World_Widget_C_SetText) == 0x000008, "Wrong alignment on WB_CaptureTheFlag_World_Widget_C_SetText");
static_assert(sizeof(WB_CaptureTheFlag_World_Widget_C_SetText) == 0x000018, "Wrong size on WB_CaptureTheFlag_World_Widget_C_SetText");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_SetText, NewText) == 0x000000, "Member 'WB_CaptureTheFlag_World_Widget_C_SetText::NewText' has a wrong offset!");

// Function WB_CaptureTheFlag_World_Widget.WB_CaptureTheFlag_World_Widget_C.SetObjectiveText
// 0x0018 (0x0018 - 0x0000)
struct WB_CaptureTheFlag_World_Widget_C_SetObjectiveText final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(WB_CaptureTheFlag_World_Widget_C_SetObjectiveText) == 0x000008, "Wrong alignment on WB_CaptureTheFlag_World_Widget_C_SetObjectiveText");
static_assert(sizeof(WB_CaptureTheFlag_World_Widget_C_SetObjectiveText) == 0x000018, "Wrong size on WB_CaptureTheFlag_World_Widget_C_SetObjectiveText");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_SetObjectiveText, Text) == 0x000000, "Member 'WB_CaptureTheFlag_World_Widget_C_SetObjectiveText::Text' has a wrong offset!");

// Function WB_CaptureTheFlag_World_Widget.WB_CaptureTheFlag_World_Widget_C.SetIconColor
// 0x0010 (0x0010 - 0x0000)
struct WB_CaptureTheFlag_World_Widget_C_SetIconColor final
{
public:
	struct FLinearColor                           Color;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_CaptureTheFlag_World_Widget_C_SetIconColor) == 0x000004, "Wrong alignment on WB_CaptureTheFlag_World_Widget_C_SetIconColor");
static_assert(sizeof(WB_CaptureTheFlag_World_Widget_C_SetIconColor) == 0x000010, "Wrong size on WB_CaptureTheFlag_World_Widget_C_SetIconColor");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_SetIconColor, Color) == 0x000000, "Member 'WB_CaptureTheFlag_World_Widget_C_SetIconColor::Color' has a wrong offset!");

// Function WB_CaptureTheFlag_World_Widget.WB_CaptureTheFlag_World_Widget_C.ExecuteUbergraph_WB_CaptureTheFlag_World_Widget
// 0x01E8 (0x01E8 - 0x0000)
struct WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         CallFunc_GetPlayerTeamFromPlayerState_Team;        // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0028(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0038(0x0018)()
	class FText                                   Temp_text_Variable_1;                              // 0x0050(0x0018)()
	class FText                                   K2Node_CustomEvent_NewText;                        // 0x0068(0x0018)()
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_CustomEvent_Text;                           // 0x0088(0x0018)()
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue_1;              // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A9[0x3];                                       // 0x00A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x00AC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_CustomEvent_Color;                          // 0x00B8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x00C8(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x00F0(0x0028)()
	bool                                          CallFunc_Conv_IntToBool_ReturnValue;               // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0119(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11A[0x2];                                      // 0x011A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_SelectColor_ReturnValue;                  // 0x011C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x012C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x0138(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0144(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_145[0x3];                                      // 0x0145(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_VSize_ReturnValue;                        // 0x0148(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x014C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_Select_Default;                             // 0x0150(0x0018)()
	class FText                                   CallFunc_Conv_FloatToText_ReturnValue;             // 0x0168(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0180(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x01C0(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x01D0(0x0018)()
};
static_assert(alignof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget) == 0x000008, "Wrong alignment on WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget");
static_assert(sizeof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget) == 0x0001E8, "Wrong size on WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, EntryPoint) == 0x000000, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::EntryPoint' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_GetPlayerPawn_ReturnValue) == 0x000008, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_GetPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_GetPlayerTeamFromPlayerState_Team) == 0x000020, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_GetPlayerTeamFromPlayerState_Team' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000028, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, Temp_bool_Variable) == 0x000030, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, Temp_text_Variable) == 0x000038, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, Temp_text_Variable_1) == 0x000050, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::Temp_text_Variable_1' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, K2Node_CustomEvent_NewText) == 0x000068, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::K2Node_CustomEvent_NewText' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_PlayAnimation_ReturnValue) == 0x000080, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, K2Node_CustomEvent_Text) == 0x000088, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::K2Node_CustomEvent_Text' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_GetPlayerPawn_ReturnValue_1) == 0x0000A0, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_GetPlayerPawn_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_IsValid_ReturnValue) == 0x0000A8, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_K2_GetActorLocation_ReturnValue) == 0x0000AC, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, K2Node_CustomEvent_Color) == 0x0000B8, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::K2Node_CustomEvent_Color' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, K2Node_MakeStruct_SlateColor) == 0x0000C8, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, K2Node_MakeStruct_SlateColor_1) == 0x0000F0, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::K2Node_MakeStruct_SlateColor_1' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_Conv_IntToBool_ReturnValue) == 0x000118, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_Conv_IntToBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_IsValid_ReturnValue_1) == 0x000119, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_SelectColor_ReturnValue) == 0x00011C, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_SelectColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x00012C, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_Subtract_VectorVector_ReturnValue) == 0x000138, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000144, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_VSize_ReturnValue) == 0x000148, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_VSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_Divide_FloatFloat_ReturnValue) == 0x00014C, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, K2Node_Select_Default) == 0x000150, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_Conv_FloatToText_ReturnValue) == 0x000168, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_Conv_FloatToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, K2Node_MakeStruct_FormatArgumentData) == 0x000180, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, K2Node_MakeArray_Array) == 0x0001C0, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget, CallFunc_Format_ReturnValue) == 0x0001D0, "Member 'WB_CaptureTheFlag_World_Widget_C_ExecuteUbergraph_WB_CaptureTheFlag_World_Widget::CallFunc_Format_ReturnValue' has a wrong offset!");

}

