#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_ConquestObjectiveProgressBar

#include "Basic.hpp"

#include "WB_ConquestObjectiveProgressBar_classes.hpp"
#include "WB_ConquestObjectiveProgressBar_parameters.hpp"


namespace SDK
{

// Function WB_ConquestObjectiveProgressBar.WB_ConquestObjectiveProgressBar_C.UpdateCapturingPointState
// (BlueprintCallable, BlueprintEvent)

void UWB_ConquestObjectiveProgressBar_C::UpdateCapturingPointState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ConquestObjectiveProgressBar_C", "UpdateCapturingPointState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_ConquestObjectiveProgressBar.WB_ConquestObjectiveProgressBar_C.SetCapturingPoint
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ECapturePoints                          ActualCapturePoint_0                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_ConquestObjectiveProgressBar_C::SetCapturingPoint(ECapturePoints ActualCapturePoint_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ConquestObjectiveProgressBar_C", "SetCapturingPoint");

	Params::WB_ConquestObjectiveProgressBar_C_SetCapturingPoint Parms{};

	Parms.ActualCapturePoint_0 = ActualCapturePoint_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_ConquestObjectiveProgressBar.WB_ConquestObjectiveProgressBar_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWB_ConquestObjectiveProgressBar_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ConquestObjectiveProgressBar_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_ConquestObjectiveProgressBar.WB_ConquestObjectiveProgressBar_C.ExecuteUbergraph_WB_ConquestObjectiveProgressBar
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_ConquestObjectiveProgressBar_C::ExecuteUbergraph_WB_ConquestObjectiveProgressBar(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ConquestObjectiveProgressBar_C", "ExecuteUbergraph_WB_ConquestObjectiveProgressBar");

	Params::WB_ConquestObjectiveProgressBar_C_ExecuteUbergraph_WB_ConquestObjectiveProgressBar Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

