#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_ConquestObjective

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WB_ConquestObjective.WB_ConquestObjective_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WB_ConquestObjective_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WB_ConquestObjective_C_PreConstruct) == 0x000001, "Wrong alignment on WB_ConquestObjective_C_PreConstruct");
static_assert(sizeof(WB_ConquestObjective_C_PreConstruct) == 0x000001, "Wrong size on WB_ConquestObjective_C_PreConstruct");
static_assert(offsetof(WB_ConquestObjective_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WB_ConquestObjective_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WB_ConquestObjective.WB_ConquestObjective_C.UpdatePercent
// 0x0004 (0x0004 - 0x0000)
struct WB_ConquestObjective_C_UpdatePercent final
{
public:
	float                                         Percent_0;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ConquestObjective_C_UpdatePercent) == 0x000004, "Wrong alignment on WB_ConquestObjective_C_UpdatePercent");
static_assert(sizeof(WB_ConquestObjective_C_UpdatePercent) == 0x000004, "Wrong size on WB_ConquestObjective_C_UpdatePercent");
static_assert(offsetof(WB_ConquestObjective_C_UpdatePercent, Percent_0) == 0x000000, "Member 'WB_ConquestObjective_C_UpdatePercent::Percent_0' has a wrong offset!");

// Function WB_ConquestObjective.WB_ConquestObjective_C.UpdateColor
// 0x0010 (0x0010 - 0x0000)
struct WB_ConquestObjective_C_UpdateColor final
{
public:
	struct FLinearColor                           Color_0;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ConquestObjective_C_UpdateColor) == 0x000004, "Wrong alignment on WB_ConquestObjective_C_UpdateColor");
static_assert(sizeof(WB_ConquestObjective_C_UpdateColor) == 0x000010, "Wrong size on WB_ConquestObjective_C_UpdateColor");
static_assert(offsetof(WB_ConquestObjective_C_UpdateColor, Color_0) == 0x000000, "Member 'WB_ConquestObjective_C_UpdateColor::Color_0' has a wrong offset!");

// Function WB_ConquestObjective.WB_ConquestObjective_C.UpdateTextColor
// 0x0010 (0x0010 - 0x0000)
struct WB_ConquestObjective_C_UpdateTextColor final
{
public:
	struct FLinearColor                           Color_0;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ConquestObjective_C_UpdateTextColor) == 0x000004, "Wrong alignment on WB_ConquestObjective_C_UpdateTextColor");
static_assert(sizeof(WB_ConquestObjective_C_UpdateTextColor) == 0x000010, "Wrong size on WB_ConquestObjective_C_UpdateTextColor");
static_assert(offsetof(WB_ConquestObjective_C_UpdateTextColor, Color_0) == 0x000000, "Member 'WB_ConquestObjective_C_UpdateTextColor::Color_0' has a wrong offset!");

// Function WB_ConquestObjective.WB_ConquestObjective_C.ExecuteUbergraph_WB_ConquestObjective
// 0x0060 (0x0060 - 0x0000)
struct WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_CustomEvent_Percent;                        // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_CustomEvent_Color_1;                        // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_CustomEvent_Color;                          // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0038(0x0028)()
};
static_assert(alignof(WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective) == 0x000008, "Wrong alignment on WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective");
static_assert(sizeof(WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective) == 0x000060, "Wrong size on WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective");
static_assert(offsetof(WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective, EntryPoint) == 0x000000, "Member 'WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective::EntryPoint' has a wrong offset!");
static_assert(offsetof(WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective, K2Node_Event_IsDesignTime) == 0x000004, "Member 'WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective, K2Node_CustomEvent_Percent) == 0x000008, "Member 'WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective::K2Node_CustomEvent_Percent' has a wrong offset!");
static_assert(offsetof(WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000010, "Member 'WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective, K2Node_CustomEvent_Color_1) == 0x000018, "Member 'WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective::K2Node_CustomEvent_Color_1' has a wrong offset!");
static_assert(offsetof(WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective, K2Node_CustomEvent_Color) == 0x000028, "Member 'WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective::K2Node_CustomEvent_Color' has a wrong offset!");
static_assert(offsetof(WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective, K2Node_MakeStruct_SlateColor) == 0x000038, "Member 'WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective::K2Node_MakeStruct_SlateColor' has a wrong offset!");

}

