#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_CaptureTheFlag_World_Widget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_CaptureTheFlag_World_Widget.WB_CaptureTheFlag_World_Widget_C
// 0x0040 (0x02A0 - 0x0260)
class UWB_CaptureTheFlag_World_Widget_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       IconAnimation;                                     // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UTextBlock*                             DistanceText;                                      // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ObjectiveIcon;                                     // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ObjectiveText;                                     // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FVector                                ObjetiveLocation;                                  // 0x0288(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Team;                                              // 0x0294(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Objective;                                         // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SetText(const class FText& NewText);
	void OnActivation();
	void On_Defuse();
	void SetObjectiveText(const class FText& Text);
	void Construct();
	void Update_Distance();
	void SetIconColor(const struct FLinearColor& Color);
	void ExecuteUbergraph_WB_CaptureTheFlag_World_Widget(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_CaptureTheFlag_World_Widget_C">();
	}
	static class UWB_CaptureTheFlag_World_Widget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_CaptureTheFlag_World_Widget_C>();
	}
};
static_assert(alignof(UWB_CaptureTheFlag_World_Widget_C) == 0x000008, "Wrong alignment on UWB_CaptureTheFlag_World_Widget_C");
static_assert(sizeof(UWB_CaptureTheFlag_World_Widget_C) == 0x0002A0, "Wrong size on UWB_CaptureTheFlag_World_Widget_C");
static_assert(offsetof(UWB_CaptureTheFlag_World_Widget_C, UberGraphFrame) == 0x000260, "Member 'UWB_CaptureTheFlag_World_Widget_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWB_CaptureTheFlag_World_Widget_C, IconAnimation) == 0x000268, "Member 'UWB_CaptureTheFlag_World_Widget_C::IconAnimation' has a wrong offset!");
static_assert(offsetof(UWB_CaptureTheFlag_World_Widget_C, DistanceText) == 0x000270, "Member 'UWB_CaptureTheFlag_World_Widget_C::DistanceText' has a wrong offset!");
static_assert(offsetof(UWB_CaptureTheFlag_World_Widget_C, ObjectiveIcon) == 0x000278, "Member 'UWB_CaptureTheFlag_World_Widget_C::ObjectiveIcon' has a wrong offset!");
static_assert(offsetof(UWB_CaptureTheFlag_World_Widget_C, ObjectiveText) == 0x000280, "Member 'UWB_CaptureTheFlag_World_Widget_C::ObjectiveText' has a wrong offset!");
static_assert(offsetof(UWB_CaptureTheFlag_World_Widget_C, ObjetiveLocation) == 0x000288, "Member 'UWB_CaptureTheFlag_World_Widget_C::ObjetiveLocation' has a wrong offset!");
static_assert(offsetof(UWB_CaptureTheFlag_World_Widget_C, Team) == 0x000294, "Member 'UWB_CaptureTheFlag_World_Widget_C::Team' has a wrong offset!");
static_assert(offsetof(UWB_CaptureTheFlag_World_Widget_C, Objective) == 0x000298, "Member 'UWB_CaptureTheFlag_World_Widget_C::Objective' has a wrong offset!");

}

