#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_Controls

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_Controls.WB_Controls_C
// 0x0000 (0x0260 - 0x0260)
class UWB_Controls_C final : public UUserWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_Controls_C">();
	}
	static class UWB_Controls_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_Controls_C>();
	}
};
static_assert(alignof(UWB_Controls_C) == 0x000008, "Wrong alignment on UWB_Controls_C");
static_assert(sizeof(UWB_Controls_C) == 0x000260, "Wrong size on UWB_Controls_C");

}

