#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_ChatText

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_ChatText.WB_ChatText_C
// 0x0050 (0x02B0 - 0x0260)
class UWB_ChatText_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             MessageWidget;                                     // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   ActualTest;                                        // 0x0270(0x0018)(Edit, BlueprintVisible, Net, ExposeOnSpawn)
	bool                                          bTeamChat;                                         // 0x0288(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          bServerMessage;                                    // 0x0289(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	uint8                                         Pad_28A[0x2];                                      // 0x028A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           DefautlFontColor;                                  // 0x028C(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           TeamChatFontColor;                                 // 0x029C(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	struct FSlateColor GetTextColor();
	void Construct();
	void ExecuteUbergraph_WB_ChatText(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_ChatText_C">();
	}
	static class UWB_ChatText_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_ChatText_C>();
	}
};
static_assert(alignof(UWB_ChatText_C) == 0x000008, "Wrong alignment on UWB_ChatText_C");
static_assert(sizeof(UWB_ChatText_C) == 0x0002B0, "Wrong size on UWB_ChatText_C");
static_assert(offsetof(UWB_ChatText_C, UberGraphFrame) == 0x000260, "Member 'UWB_ChatText_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWB_ChatText_C, MessageWidget) == 0x000268, "Member 'UWB_ChatText_C::MessageWidget' has a wrong offset!");
static_assert(offsetof(UWB_ChatText_C, ActualTest) == 0x000270, "Member 'UWB_ChatText_C::ActualTest' has a wrong offset!");
static_assert(offsetof(UWB_ChatText_C, bTeamChat) == 0x000288, "Member 'UWB_ChatText_C::bTeamChat' has a wrong offset!");
static_assert(offsetof(UWB_ChatText_C, bServerMessage) == 0x000289, "Member 'UWB_ChatText_C::bServerMessage' has a wrong offset!");
static_assert(offsetof(UWB_ChatText_C, DefautlFontColor) == 0x00028C, "Member 'UWB_ChatText_C::DefautlFontColor' has a wrong offset!");
static_assert(offsetof(UWB_ChatText_C, TeamChatFontColor) == 0x00029C, "Member 'UWB_ChatText_C::TeamChatFontColor' has a wrong offset!");

}

