#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_DirectionalDamageIndicator

#include "Basic.hpp"

#include "WB_DirectionalDamageIndicator_classes.hpp"
#include "WB_DirectionalDamageIndicator_parameters.hpp"


namespace SDK
{

// Function WB_DirectionalDamageIndicator.WB_DirectionalDamageIndicator_C.RotateWidget
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_DirectionalDamageIndicator_C::RotateWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_DirectionalDamageIndicator_C", "RotateWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_DirectionalDamageIndicator.WB_DirectionalDamageIndicator_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWB_DirectionalDamageIndicator_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_DirectionalDamageIndicator_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_DirectionalDamageIndicator.WB_DirectionalDamageIndicator_C.ExecuteUbergraph_WB_DirectionalDamageIndicator
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_DirectionalDamageIndicator_C::ExecuteUbergraph_WB_DirectionalDamageIndicator(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_DirectionalDamageIndicator_C", "ExecuteUbergraph_WB_DirectionalDamageIndicator");

	Params::WB_DirectionalDamageIndicator_C_ExecuteUbergraph_WB_DirectionalDamageIndicator Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

