#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_DirectionalDamageIndicator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_DirectionalDamageIndicator.WB_DirectionalDamageIndicator_C
// 0x0038 (0x0298 - 0x0260)
class UWB_DirectionalDamageIndicator_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       DamageIndicatorAnim;                               // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanel*                           Canvas;                                            // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IndicatorImage;                                    // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	float                                         Angle;                                             // 0x0280(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                DmgLocation;                                       // 0x0284(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class APawn*                                  PlayerPawn;                                        // 0x0290(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void RotateWidget();
	void Construct();
	void ExecuteUbergraph_WB_DirectionalDamageIndicator(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_DirectionalDamageIndicator_C">();
	}
	static class UWB_DirectionalDamageIndicator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_DirectionalDamageIndicator_C>();
	}
};
static_assert(alignof(UWB_DirectionalDamageIndicator_C) == 0x000008, "Wrong alignment on UWB_DirectionalDamageIndicator_C");
static_assert(sizeof(UWB_DirectionalDamageIndicator_C) == 0x000298, "Wrong size on UWB_DirectionalDamageIndicator_C");
static_assert(offsetof(UWB_DirectionalDamageIndicator_C, UberGraphFrame) == 0x000260, "Member 'UWB_DirectionalDamageIndicator_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWB_DirectionalDamageIndicator_C, DamageIndicatorAnim) == 0x000268, "Member 'UWB_DirectionalDamageIndicator_C::DamageIndicatorAnim' has a wrong offset!");
static_assert(offsetof(UWB_DirectionalDamageIndicator_C, Canvas) == 0x000270, "Member 'UWB_DirectionalDamageIndicator_C::Canvas' has a wrong offset!");
static_assert(offsetof(UWB_DirectionalDamageIndicator_C, IndicatorImage) == 0x000278, "Member 'UWB_DirectionalDamageIndicator_C::IndicatorImage' has a wrong offset!");
static_assert(offsetof(UWB_DirectionalDamageIndicator_C, Angle) == 0x000280, "Member 'UWB_DirectionalDamageIndicator_C::Angle' has a wrong offset!");
static_assert(offsetof(UWB_DirectionalDamageIndicator_C, DmgLocation) == 0x000284, "Member 'UWB_DirectionalDamageIndicator_C::DmgLocation' has a wrong offset!");
static_assert(offsetof(UWB_DirectionalDamageIndicator_C, PlayerPawn) == 0x000290, "Member 'UWB_DirectionalDamageIndicator_C::PlayerPawn' has a wrong offset!");

}

