#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_Explosive_Icon

#include "Basic.hpp"

#include "WB_Explosive_Icon_classes.hpp"
#include "WB_Explosive_Icon_parameters.hpp"


namespace SDK
{

// Function WB_Explosive_Icon.WB_Explosive_Icon_C.OnOwnerDeath
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_Explosive_Icon_C::OnOwnerDeath()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "OnOwnerDeath");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.ShowHitMarker
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bVehicle                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Explosive_Icon_C::ShowHitMarker(bool bVehicle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "ShowHitMarker");

	Params::WB_Explosive_Icon_C_ShowHitMarker Parms{};

	Parms.bVehicle = bVehicle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.ShowKillMarker
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_Explosive_Icon_C::ShowKillMarker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "ShowKillMarker");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.UpdateFiringMode
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EFiringMode                             NewFiringMode                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Explosive_Icon_C::UpdateFiringMode(EFiringMode NewFiringMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "UpdateFiringMode");

	Params::WB_Explosive_Icon_C_UpdateFiringMode Parms{};

	Parms.NewFiringMode = NewFiringMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.UpdateHP
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   NewHP                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   MaxHP                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Explosive_Icon_C::UpdateHP(float NewHP, float MaxHP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "UpdateHP");

	Params::WB_Explosive_Icon_C_UpdateHP Parms{};

	Parms.NewHP = NewHP;
	Parms.MaxHP = MaxHP;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.UpdateCurrentBullets
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   CurrentBullets                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   BulletsPerMag                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Explosive_Icon_C::UpdateCurrentBullets(int32 CurrentBullets, int32 BulletsPerMag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "UpdateCurrentBullets");

	Params::WB_Explosive_Icon_C_UpdateCurrentBullets Parms{};

	Parms.CurrentBullets = CurrentBullets;
	Parms.BulletsPerMag = BulletsPerMag;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.UpdateTotalBullets
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TotalBullets                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Explosive_Icon_C::UpdateTotalBullets(int32 TotalBullets)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "UpdateTotalBullets");

	Params::WB_Explosive_Icon_C_UpdateTotalBullets Parms{};

	Parms.TotalBullets = TotalBullets;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.ShowHitOverlay
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_Explosive_Icon_C::ShowHitOverlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "ShowHitOverlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.UpdateMatchTimer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   TimeInSeconds                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Explosive_Icon_C::UpdateMatchTimer(float TimeInSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "UpdateMatchTimer");

	Params::WB_Explosive_Icon_C_UpdateMatchTimer Parms{};

	Parms.TimeInSeconds = TimeInSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.UpdateGameModeScores
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeamAPoints                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TeamBPoints                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   PointsToWin                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Explosive_Icon_C::UpdateGameModeScores(int32 TeamAPoints, int32 TeamBPoints, int32 PointsToWin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "UpdateGameModeScores");

	Params::WB_Explosive_Icon_C_UpdateGameModeScores Parms{};

	Parms.TeamAPoints = TeamAPoints;
	Parms.TeamBPoints = TeamBPoints;
	Parms.PointsToWin = PointsToWin;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.UpdateKillFeed
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerState*                     Killer                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APlayerState*                     Victim                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UDamageType*                      DamageType                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APlayerState*                     Assist                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bHeadshot                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Explosive_Icon_C::UpdateKillFeed(class APlayerState* Killer, class APlayerState* Victim, const class UDamageType* DamageType, class APlayerState* Assist, bool bHeadshot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "UpdateKillFeed");

	Params::WB_Explosive_Icon_C_UpdateKillFeed Parms{};

	Parms.Killer = Killer;
	Parms.Victim = Victim;
	Parms.DamageType = DamageType;
	Parms.Assist = Assist;
	Parms.bHeadshot = bHeadshot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.ShowScore
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Score                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             Reason                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UWB_Explosive_Icon_C::ShowScore(float Score, const class FText& Reason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "ShowScore");

	Params::WB_Explosive_Icon_C_ShowScore Parms{};

	Parms.Score = Score;
	Parms.Reason = std::move(Reason);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.HideWeaponInfo
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_Explosive_Icon_C::HideWeaponInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "HideWeaponInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.UpdateObjectiveMarkers
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Base_Objective_C*             ObjectiveToUpdate                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    PlayIconAnim                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   Team                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Explosive_Icon_C::UpdateObjectiveMarkers(class ABP_Base_Objective_C* ObjectiveToUpdate, bool PlayIconAnim, int32 Team)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "UpdateObjectiveMarkers");

	Params::WB_Explosive_Icon_C_UpdateObjectiveMarkers Parms{};

	Parms.ObjectiveToUpdate = ObjectiveToUpdate;
	Parms.PlayIconAnim = PlayIconAnim;
	Parms.Team = Team;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.ShowInteractProgressBar
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   InteractTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Explosive_Icon_C::ShowInteractProgressBar(float InteractTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "ShowInteractProgressBar");

	Params::WB_Explosive_Icon_C_ShowInteractProgressBar Parms{};

	Parms.InteractTime = InteractTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.HideInteractProgressBar
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_Explosive_Icon_C::HideInteractProgressBar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "HideInteractProgressBar");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.ShowHealOverlay
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_Explosive_Icon_C::ShowHealOverlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "ShowHealOverlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.ShowInteractInfo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Description                                            (BlueprintVisible, BlueprintReadOnly, Parm)

void UWB_Explosive_Icon_C::ShowInteractInfo(const class FText& Description)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "ShowInteractInfo");

	Params::WB_Explosive_Icon_C_ShowInteractInfo Parms{};

	Parms.Description = std::move(Description);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.HideInteractInfo
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_Explosive_Icon_C::HideInteractInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "HideInteractInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.ShowAbilityCooldownTime
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   TimeRemaining                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Explosive_Icon_C::ShowAbilityCooldownTime(float TimeRemaining)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "ShowAbilityCooldownTime");

	Params::WB_Explosive_Icon_C_ShowAbilityCooldownTime Parms{};

	Parms.TimeRemaining = TimeRemaining;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.UpdateExplosives
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ExplosivesAmount                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture*                         Icon_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Explosive_Icon_C::UpdateExplosives(int32 ExplosivesAmount, class UTexture* Icon_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "UpdateExplosives");

	Params::WB_Explosive_Icon_C_UpdateExplosives Parms{};

	Parms.ExplosivesAmount = ExplosivesAmount;
	Parms.Icon_0 = Icon_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.UpdateRushScores
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Reinforcements                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TotalReinforcements                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Explosive_Icon_C::UpdateRushScores(int32 Reinforcements, int32 TotalReinforcements)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "UpdateRushScores");

	Params::WB_Explosive_Icon_C_UpdateRushScores Parms{};

	Parms.Reinforcements = Reinforcements;
	Parms.TotalReinforcements = TotalReinforcements;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.UpdateDeathmatchScores
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           WinnerName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int32                                   WinnerKills                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   KillsToWin                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Explosive_Icon_C::UpdateDeathmatchScores(const class FString& WinnerName, int32 WinnerKills, int32 KillsToWin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "UpdateDeathmatchScores");

	Params::WB_Explosive_Icon_C_UpdateDeathmatchScores Parms{};

	Parms.WinnerName = std::move(WinnerName);
	Parms.WinnerKills = WinnerKills;
	Parms.KillsToWin = KillsToWin;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.UpdateTeamIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture*                         TeamIcon                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Explosive_Icon_C::UpdateTeamIcon(class UTexture* TeamIcon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "UpdateTeamIcon");

	Params::WB_Explosive_Icon_C_UpdateTeamIcon Parms{};

	Parms.TeamIcon = TeamIcon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.ShowCrouchIcon
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_Explosive_Icon_C::ShowCrouchIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "ShowCrouchIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.ShowStandingIcon
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_Explosive_Icon_C::ShowStandingIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "ShowStandingIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.UpdateSkillIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       SkillIcon                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Explosive_Icon_C::UpdateSkillIcon(class UTexture2D* SkillIcon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "UpdateSkillIcon");

	Params::WB_Explosive_Icon_C_UpdateSkillIcon Parms{};

	Parms.SkillIcon = SkillIcon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.SetWidgetVisibility
// (BlueprintCallable, BlueprintEvent)

void UWB_Explosive_Icon_C::SetWidgetVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "SetWidgetVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.ShowWidget
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_Explosive_Icon_C::ShowWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "ShowWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.HideWidget
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_Explosive_Icon_C::HideWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "HideWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Explosive_Icon.WB_Explosive_Icon_C.ExecuteUbergraph_WB_Explosive_Icon
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Explosive_Icon_C::ExecuteUbergraph_WB_Explosive_Icon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Explosive_Icon_C", "ExecuteUbergraph_WB_Explosive_Icon");

	Params::WB_Explosive_Icon_C_ExecuteUbergraph_WB_Explosive_Icon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

