#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_HUD

#include "Basic.hpp"

#include "WB_HUD_classes.hpp"
#include "WB_HUD_parameters.hpp"


namespace SDK
{

// Function WB_HUD.WB_HUD_C.UpdateTimer
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   TimeInSeconds                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::UpdateTimer(float TimeInSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "UpdateTimer");

	Params::WB_HUD_C_UpdateTimer Parms{};

	Parms.TimeInSeconds = TimeInSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.RotateDamageCanvas
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::RotateDamageCanvas()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "RotateDamageCanvas");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.RotateCompass
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::RotateCompass()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "RotateCompass");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.UpdateObjectiveMarkers
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Base_Objective_C*             ObjectiveToUpdate                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    PlayIconAnim                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   Team                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::UpdateObjectiveMarkers(class ABP_Base_Objective_C* ObjectiveToUpdate, bool PlayIconAnim, int32 Team)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "UpdateObjectiveMarkers");

	Params::WB_HUD_C_UpdateObjectiveMarkers Parms{};

	Parms.ObjectiveToUpdate = ObjectiveToUpdate;
	Parms.PlayIconAnim = PlayIconAnim;
	Parms.Team = Team;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.ToogleInteractText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bVisible                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_HUD_C::ToogleInteractText(bool bVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "ToogleInteractText");

	Params::WB_HUD_C_ToogleInteractText Parms{};

	Parms.bVisible = bVisible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.UpdateGameModeScores
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeamAPoints                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TeamBPoints                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   PointsToWin                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::UpdateGameModeScores(int32 TeamAPoints, int32 TeamBPoints, int32 PointsToWin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "UpdateGameModeScores");

	Params::WB_HUD_C_UpdateGameModeScores Parms{};

	Parms.TeamAPoints = TeamAPoints;
	Parms.TeamBPoints = TeamBPoints;
	Parms.PointsToWin = PointsToWin;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.SetWeaponAmmoInfoVisibility
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ESlateVisibility                        Visibility_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::SetWeaponAmmoInfoVisibility(ESlateVisibility Visibility_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "SetWeaponAmmoInfoVisibility");

	Params::WB_HUD_C_SetWeaponAmmoInfoVisibility Parms{};

	Parms.Visibility_0 = Visibility_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.ShowHitMarker
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bVehicle                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_HUD_C::ShowHitMarker(bool bVehicle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "ShowHitMarker");

	Params::WB_HUD_C_ShowHitMarker Parms{};

	Parms.bVehicle = bVehicle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.ShowKillMarker
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::ShowKillMarker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "ShowKillMarker");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.UpdateFiringMode
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EFiringMode                             NewFiringMode                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::UpdateFiringMode(EFiringMode NewFiringMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "UpdateFiringMode");

	Params::WB_HUD_C_UpdateFiringMode Parms{};

	Parms.NewFiringMode = NewFiringMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.OnOwnerDeath
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::OnOwnerDeath()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "OnOwnerDeath");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.UpdateHP
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   NewHP                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   MaxHP                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::UpdateHP(float NewHP, float MaxHP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "UpdateHP");

	Params::WB_HUD_C_UpdateHP Parms{};

	Parms.NewHP = NewHP;
	Parms.MaxHP = MaxHP;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.UpdateCurrentBullets
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   CurrentBullets_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   BulletsPerMag                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::UpdateCurrentBullets(int32 CurrentBullets_0, int32 BulletsPerMag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "UpdateCurrentBullets");

	Params::WB_HUD_C_UpdateCurrentBullets Parms{};

	Parms.CurrentBullets_0 = CurrentBullets_0;
	Parms.BulletsPerMag = BulletsPerMag;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.UpdateTotalBullets
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TotalBullets_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::UpdateTotalBullets(int32 TotalBullets_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "UpdateTotalBullets");

	Params::WB_HUD_C_UpdateTotalBullets Parms{};

	Parms.TotalBullets_0 = TotalBullets_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.UpdateMatchTimer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   TimeInSeconds                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::UpdateMatchTimer(float TimeInSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "UpdateMatchTimer");

	Params::WB_HUD_C_UpdateMatchTimer Parms{};

	Parms.TimeInSeconds = TimeInSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.UpdateKillFeed
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerState*                     Killer                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APlayerState*                     Victim                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UDamageType*                      DamageType                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APlayerState*                     Assist                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bHeadshot                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_HUD_C::UpdateKillFeed(class APlayerState* Killer, class APlayerState* Victim, const class UDamageType* DamageType, class APlayerState* Assist, bool bHeadshot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "UpdateKillFeed");

	Params::WB_HUD_C_UpdateKillFeed Parms{};

	Parms.Killer = Killer;
	Parms.Victim = Victim;
	Parms.DamageType = DamageType;
	Parms.Assist = Assist;
	Parms.bHeadshot = bHeadshot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.ShowHitOverlay
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::ShowHitOverlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "ShowHitOverlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.ShowScore
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Score                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             Reason                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UWB_HUD_C::ShowScore(float Score, const class FText& Reason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "ShowScore");

	Params::WB_HUD_C_ShowScore Parms{};

	Parms.Score = Score;
	Parms.Reason = std::move(Reason);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.HideWeaponInfo
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::HideWeaponInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "HideWeaponInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.ShowInteractProgressBar
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   InteractTime_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::ShowInteractProgressBar(float InteractTime_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "ShowInteractProgressBar");

	Params::WB_HUD_C_ShowInteractProgressBar Parms{};

	Parms.InteractTime_0 = InteractTime_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.HideInteractProgressBar
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::HideInteractProgressBar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "HideInteractProgressBar");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.UpdateProgressBar
// (BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::UpdateProgressBar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "UpdateProgressBar");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.ShowHealOverlay
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::ShowHealOverlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "ShowHealOverlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.ShowInteractInfo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Description                                            (BlueprintVisible, BlueprintReadOnly, Parm)

void UWB_HUD_C::ShowInteractInfo(const class FText& Description)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "ShowInteractInfo");

	Params::WB_HUD_C_ShowInteractInfo Parms{};

	Parms.Description = std::move(Description);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.HideInteractInfo
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::HideInteractInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "HideInteractInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.ShowAbilityCooldownTime
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   TimeRemaining                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::ShowAbilityCooldownTime(float TimeRemaining)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "ShowAbilityCooldownTime");

	Params::WB_HUD_C_ShowAbilityCooldownTime Parms{};

	Parms.TimeRemaining = TimeRemaining;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.UpdateCooldownTimer
// (BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::UpdateCooldownTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "UpdateCooldownTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.HideCooldownTimer
// (BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::HideCooldownTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "HideCooldownTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.UpdateExplosives
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ExplosivesAmount_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture*                         Icon                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::UpdateExplosives(int32 ExplosivesAmount_0, class UTexture* Icon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "UpdateExplosives");

	Params::WB_HUD_C_UpdateExplosives Parms{};

	Parms.ExplosivesAmount_0 = ExplosivesAmount_0;
	Parms.Icon = Icon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.OnHealthBarChange
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   TargetPercent                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::OnHealthBarChange(float TargetPercent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "OnHealthBarChange");

	Params::WB_HUD_C_OnHealthBarChange Parms{};

	Parms.TargetPercent = TargetPercent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.InterpolateToNewHealth
// (BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::InterpolateToNewHealth()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "InterpolateToNewHealth");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.AddDamageIndicator
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          DmgLocation                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::AddDamageIndicator(const struct FVector& DmgLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "AddDamageIndicator");

	Params::WB_HUD_C_AddDamageIndicator Parms{};

	Parms.DmgLocation = std::move(DmgLocation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWB_HUD_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.UpdateDeathmatchScores
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           WinnerName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int32                                   WinnerKills                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   KillsToWin                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::UpdateDeathmatchScores(const class FString& WinnerName, int32 WinnerKills, int32 KillsToWin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "UpdateDeathmatchScores");

	Params::WB_HUD_C_UpdateDeathmatchScores Parms{};

	Parms.WinnerName = std::move(WinnerName);
	Parms.WinnerKills = WinnerKills;
	Parms.KillsToWin = KillsToWin;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.UpdateTeamIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture*                         TeamIcon_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::UpdateTeamIcon(class UTexture* TeamIcon_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "UpdateTeamIcon");

	Params::WB_HUD_C_UpdateTeamIcon Parms{};

	Parms.TeamIcon_0 = TeamIcon_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.ShowCrouchIcon
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::ShowCrouchIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "ShowCrouchIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.ShowStandingIcon
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::ShowStandingIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "ShowStandingIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.UpdateRushScores
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Reinforcements                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TotalReinforcements                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::UpdateRushScores(int32 Reinforcements, int32 TotalReinforcements)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "UpdateRushScores");

	Params::WB_HUD_C_UpdateRushScores Parms{};

	Parms.Reinforcements = Reinforcements;
	Parms.TotalReinforcements = TotalReinforcements;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.ShowReloadWarning
// (BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::ShowReloadWarning()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "ShowReloadWarning");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.HideReloadWarning
// (BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::HideReloadWarning()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "HideReloadWarning");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.HideWidget
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::HideWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "HideWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.UpdateSkillIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       SkillIcon                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::UpdateSkillIcon(class UTexture2D* SkillIcon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "UpdateSkillIcon");

	Params::WB_HUD_C_UpdateSkillIcon Parms{};

	Parms.SkillIcon = SkillIcon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD.WB_HUD_C.ShowWidget
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_HUD_C::ShowWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "ShowWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD.WB_HUD_C.ExecuteUbergraph_WB_HUD
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_C::ExecuteUbergraph_WB_HUD(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_C", "ExecuteUbergraph_WB_HUD");

	Params::WB_HUD_C_ExecuteUbergraph_WB_HUD Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

