#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_KilledBy

#include "Basic.hpp"

#include "EPlayerClass_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WB_KilledBy.WB_KilledBy_C.ExecuteUbergraph_WB_KilledBy
// 0x00E0 (0x00E0 - 0x0000)
struct WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPlayerClass                                  Temp_byte_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                Temp_object_Variable;                              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                Temp_object_Variable_1;                            // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                Temp_object_Variable_2;                            // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0028(0x0018)()
	class UObject*                                K2Node_Select_Default;                             // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush;                      // 0x0048(0x0088)()
	const class UDT_BaseDamage_C*                 K2Node_DynamicCast_AsDT_Base_Damage;               // 0x00D0(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy) == 0x000008, "Wrong alignment on WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy");
static_assert(sizeof(WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy) == 0x0000E0, "Wrong size on WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy");
static_assert(offsetof(WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy, EntryPoint) == 0x000000, "Member 'WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy::EntryPoint' has a wrong offset!");
static_assert(offsetof(WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy, Temp_byte_Variable) == 0x000004, "Member 'WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy, Temp_object_Variable) == 0x000008, "Member 'WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy, Temp_object_Variable_1) == 0x000010, "Member 'WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy, Temp_object_Variable_2) == 0x000018, "Member 'WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy::Temp_object_Variable_2' has a wrong offset!");
static_assert(offsetof(WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy, CallFunc_FTrunc_ReturnValue) == 0x000020, "Member 'WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy::CallFunc_FTrunc_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy, CallFunc_Conv_IntToText_ReturnValue) == 0x000028, "Member 'WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy, K2Node_Select_Default) == 0x000040, "Member 'WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy, K2Node_MakeStruct_SlateBrush) == 0x000048, "Member 'WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy::K2Node_MakeStruct_SlateBrush' has a wrong offset!");
static_assert(offsetof(WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy, K2Node_DynamicCast_AsDT_Base_Damage) == 0x0000D0, "Member 'WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy::K2Node_DynamicCast_AsDT_Base_Damage' has a wrong offset!");
static_assert(offsetof(WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy, K2Node_DynamicCast_bSuccess) == 0x0000D8, "Member 'WB_KilledBy_C_ExecuteUbergraph_WB_KilledBy::K2Node_DynamicCast_bSuccess' has a wrong offset!");

}

