#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_PlayerTag

#include "Basic.hpp"

#include "WB_PlayerTag_classes.hpp"
#include "WB_PlayerTag_parameters.hpp"


namespace SDK
{

// Function WB_PlayerTag.WB_PlayerTag_C.SetDisplayedName
// (BlueprintCallable, BlueprintEvent)

void UWB_PlayerTag_C::SetDisplayedName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_PlayerTag_C", "SetDisplayedName");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_PlayerTag.WB_PlayerTag_C.ShowName
// (BlueprintCallable, BlueprintEvent)

void UWB_PlayerTag_C::ShowName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_PlayerTag_C", "ShowName");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_PlayerTag.WB_PlayerTag_C.Show EnemyTag
// (BlueprintCallable, BlueprintEvent)

void UWB_PlayerTag_C::Show_EnemyTag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_PlayerTag_C", "Show EnemyTag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_PlayerTag.WB_PlayerTag_C.UpdateTags
// (BlueprintCallable, BlueprintEvent)

void UWB_PlayerTag_C::UpdateTags()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_PlayerTag_C", "UpdateTags");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_PlayerTag.WB_PlayerTag_C.ExecuteUbergraph_WB_PlayerTag
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_PlayerTag_C::ExecuteUbergraph_WB_PlayerTag(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_PlayerTag_C", "ExecuteUbergraph_WB_PlayerTag");

	Params::WB_PlayerTag_C_ExecuteUbergraph_WB_PlayerTag Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

