#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_PlayerTag

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_PlayerTag.WB_PlayerTag_C
// 0x0078 (0x02D8 - 0x0260)
class UWB_PlayerTag_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       EnemyTagAnim;                                      // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       PlayerNameAnim;                                    // 0x0270(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UTextBlock*                             NameText;                                          // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 PlayerIcon;                                        // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TeamDeathPlayerIcon;                               // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ABP_BaseCharacter_C*                    Owner;                                             // 0x0290(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           EnemyColor;                                        // 0x0298(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           AllyColor;                                         // 0x02A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsDM;                                             // 0x02B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B9[0x7];                                      // 0x02B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   PlayerName;                                        // 0x02C0(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void SetDisplayedName();
	void ShowName();
	void Show_EnemyTag();
	void UpdateTags();
	void ExecuteUbergraph_WB_PlayerTag(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_PlayerTag_C">();
	}
	static class UWB_PlayerTag_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_PlayerTag_C>();
	}
};
static_assert(alignof(UWB_PlayerTag_C) == 0x000008, "Wrong alignment on UWB_PlayerTag_C");
static_assert(sizeof(UWB_PlayerTag_C) == 0x0002D8, "Wrong size on UWB_PlayerTag_C");
static_assert(offsetof(UWB_PlayerTag_C, UberGraphFrame) == 0x000260, "Member 'UWB_PlayerTag_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWB_PlayerTag_C, EnemyTagAnim) == 0x000268, "Member 'UWB_PlayerTag_C::EnemyTagAnim' has a wrong offset!");
static_assert(offsetof(UWB_PlayerTag_C, PlayerNameAnim) == 0x000270, "Member 'UWB_PlayerTag_C::PlayerNameAnim' has a wrong offset!");
static_assert(offsetof(UWB_PlayerTag_C, NameText) == 0x000278, "Member 'UWB_PlayerTag_C::NameText' has a wrong offset!");
static_assert(offsetof(UWB_PlayerTag_C, PlayerIcon) == 0x000280, "Member 'UWB_PlayerTag_C::PlayerIcon' has a wrong offset!");
static_assert(offsetof(UWB_PlayerTag_C, TeamDeathPlayerIcon) == 0x000288, "Member 'UWB_PlayerTag_C::TeamDeathPlayerIcon' has a wrong offset!");
static_assert(offsetof(UWB_PlayerTag_C, Owner) == 0x000290, "Member 'UWB_PlayerTag_C::Owner' has a wrong offset!");
static_assert(offsetof(UWB_PlayerTag_C, EnemyColor) == 0x000298, "Member 'UWB_PlayerTag_C::EnemyColor' has a wrong offset!");
static_assert(offsetof(UWB_PlayerTag_C, AllyColor) == 0x0002A8, "Member 'UWB_PlayerTag_C::AllyColor' has a wrong offset!");
static_assert(offsetof(UWB_PlayerTag_C, bIsDM) == 0x0002B8, "Member 'UWB_PlayerTag_C::bIsDM' has a wrong offset!");
static_assert(offsetof(UWB_PlayerTag_C, PlayerName) == 0x0002C0, "Member 'UWB_PlayerTag_C::PlayerName' has a wrong offset!");

}

